server.port=8080
spring.main.banner-mode=off
logging.level.org.springframework.web=info
spring.security.oauth2.client.registration.github.client-id=Ov23liFug0MJzfReQ4Xu
spring.security.oauth2.client.registration.github.client-secret=6c254a07539e74d2ed007789a7b9ae1365712696
spring.security.oauth2.client.registration.github.scope=read:user,repo
